services:
  postgres:
    image: ${IMAGE_POSTGRES}
    container_name: ${CONTAINER_NAME_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}"
    volumes:
      - ${POSTGRES_VOLUME_PRD}:/var/lib/postgresql/data
    networks:
      - tm_network

  pgadmin:
    image: ${IMAGE_PGADMIN}
    container_name: ${CONTAINER_NAME_PGADMIN}
    restart: always
    ports:
      - "${PGADMIN_PORT_EXTERNAL}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - tm_network

  redis:
    image: ${IMAGE_REDIS}
    container_name: ${CONTAINER_NAME_REDIS}
    ports:
      - "${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}"
    networks:
      - tm_network

  backend:
    build:
      context: ${BACKEND_CONTEXT}
      dockerfile: ${BACKEND_DOCKERFILE_DEV}
    container_name: ${CONTAINER_NAME_BACKEND}
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT_INTERNAL}
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${BACKEND_PORT_DEV}:${BACKEND_PORT_INTERNAL}"
    volumes:
      - ${BACKEND_CONTEXT}:/app
      - /app/node_modules
    networks:
      - tm_network

  minio:
    image: ${IMAGE_MINIO}
    container_name: ${CONTAINER_NAME_MINIO}
    ports:
      - "${MINIO_PORT_API}:9000"
      - "${MINIO_PORT_CONSOLE}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_PATH}:/data
    command: server /data --console-address ":9001"
    networks:
      - tm_network

  frontend:
    build:
      context: ${FRONTEND_CONTEXT}
      dockerfile: ${FRONTEND_DOCKERFILE_DEV}
    container_name: ${CONTAINER_NAME_FRONTEND}
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NODE_ENV: development
    ports:
      - "${FRONTEND_PORT_DEV}:${FRONTEND_PORT_INTERNAL}"
    volumes:
      - ${FRONTEND_CONTEXT}:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - tm_network

  nginx:
    image: ${IMAGE_NGINX}
    container_name: ${CONTAINER_NAME_NGINX}
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - tm_network

networks:
  tm_network:
    driver: bridge
