import {
    Home,
    User,
    Settings,
    Bell,
    Search,
    Eye,
    EyeOff,
    CheckCircle,
    XCircle,
    AlertCircle,
    Info,
    X,
    Menu,
    ChevronDown,
    ChevronRight,
    LogOut,
    Plus,
    Trash,
    Edit,
    Loader,
    Check,
    Users,
    Coffee,
    Briefcase,
    ArrowRight,
    ShoppingBag,
    Lock,
    UserPlus,
    Mail,
    Shield,
    CheckCircle2,
    Instagram,
    Facebook,
    Youtube,
    Twitter,
    MessageCircle,
    HelpCircle,
    MessageSquare,
    Send,
    Bot,
    AlertTriangle
} from "lucide-react";

export const ICONS = {
    home: Home,
    user: User,
    settings: Settings,
    bell: Bell,
    search: Search,
    eye: Eye,
    "eye-off": EyeOff,
    "check-circle": CheckCircle,
    "x-circle": XCircle,
    "alert-circle": AlertCircle,
    info: Info,
    close: X,
    menu: Menu,
    "chevron-down": ChevronDown,
    "chevron-right": ChevronRight,
    logout: LogOut,
    plus: Plus,
    trash: Trash,
    edit: Edit,
    loader: Loader,
    check: Check,
    users: Users,
    coffee: Coffee,
    briefcase: Briefcase,
    "arrow-right": ArrowRight,
    "shopping-bag": ShoppingBag,
    lock: Lock,
    "user-plus": UserPlus,
    mail: Mail,
    shield: Shield,
    "check-circle-2": CheckCircle2,
    instagram: Instagram,
    facebook: Facebook,
    youtube: Youtube,
    twitter: Twitter,
    whatsapp: MessageCircle,
    "help-circle": HelpCircle,
    "message-square": MessageSquare,
    send: Send,
    bot: Bot,
    "alert-triangle": AlertTriangle
} as const;

export type IconName = keyof typeof ICONS;
